name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-x64:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - name: 显示环境
        shell: pwsh
        run: |
          msbuild /version
          echo "---"
          dir "C:\Program Files\Microsoft Visual Studio\2022" -ErrorAction SilentlyContinue
          dir "C:\Program Files\Microsoft Visual Studio" -ErrorAction SilentlyContinue
      - name: 编译 x64
        shell: cmd
        run: msbuild JMSPlugin.sln /p:Configuration=Release /p:Platform=x64 /t:Rebuild /m /v:normal
      - name: 上传 DLL
        uses: actions/upload-artifact@v4
        with:
          name: JMSPlugin-x64
          path: bin\x64\Release\JMSPlugin.dll
          if-no-files-found: error

  build-Win32:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - name: 编译 Win32
        shell: cmd
        run: msbuild JMSPlugin.sln /p:Configuration=Release /p:Platform=Win32 /t:Rebuild /m /v:normal
      - name: 上传 DLL
        uses: actions/upload-artifact@v4
        with:
          name: JMSPlugin-Win32
          path: bin\Win32\Release\JMSPlugin.dll
          if-no-files-found: error
